#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.1.{build}

branches:
  only:
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: src\CommonAssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  verbosity: minimal

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%\src
  - nuget restore Georadix.sln

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir out
  - cd out
  - nuget pack "..\src\Georadix.Core\Georadix.Core.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects
  - nuget pack "..\src\Georadix.Cqs\Georadix.Cqs.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects
  - nuget pack "..\src\Georadix.EF.Testing\Georadix.EF.Testing.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects
  - nuget pack "..\src\Georadix.Web\Georadix.Web.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects
  - nuget pack "..\src\Georadix.WebApi\Georadix.WebApi.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects
  - nuget pack "..\src\Georadix.WebApi.Testing\Georadix.WebApi.Testing.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects

#---------------------------------#
#       tests configuration       #
#---------------------------------#

before_test:
  - cd %APPVEYOR_BUILD_FOLDER%\tools
  - ps: .\InstallCert.ps1

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: out\*.nupkg